# diseñado para usar un comando como el siguiente, y hacer que el contenedor se mantenga activo
# de fondo mientras se realizan pruebas con él:
#> docker run --rm -d --network bridge \
#	tfg2asircanaveral2024/3.7.1-ubuntu-networking:no-interactivo
FROM ubuntu:jammy

ENTRYPOINT ifconfig -a && sleep 1000

# instalar los paquetes con herramientas de networking que necesitamos
RUN apt update && apt install net-tools dnsutils iputils-ping -y
